--1. Revenue by Category (Strategic View)
SELECT
	P.CATEGORY,
	SUM(OI.SUBTOTAL) AS TOTAL_REVENUE
FROM
	ORDER_ITEMS OI
	INNER JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.CATEGORY
ORDER BY
	TOTAL_REVENUE DESC;

-- 2. Top Products by Revenue (Electronics)
SELECT
	P.PRODUCT_NAME,
	SUM(OI.SUBTOTAL) AS TOTAL_REVENUE,
	DENSE_RANK() OVER (
		ORDER BY
			SUM(OI.SUBTOTAL) DESC
	) AS REVENUE_RANK
FROM
	ORDER_ITEMS OI
	INNER JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
WHERE
	P.CATEGORY = 'Electronics'
GROUP BY
	P.PRODUCT_NAME
ORDER BY
	TOTAL_REVENUE DESC;

--3. Product Profitability
SELECT
	P.PRODUCT_NAME,
	SUM((OI.UNIT_PRICE - P.COST_PRICE) * OI.QUANTITY) AS TOTAL_PROFIT
FROM
	ORDER_ITEMS OI
	INNER JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.PRODUCT_NAME
ORDER BY
	TOTAL_PROFIT DESC;

--4. Customer Revenue & Order Behavior
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME,
	SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE,
	COUNT(O.ORDER_ID) AS ORDER_COUNT,
	ROUND(AVG(O.TOTAL_AMOUNT), 2) AS AVG_ORDER_VALUE
FROM
	CUSTOMERS C
	INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME
ORDER BY
	TOTAL_REVENUE DESC;

--5. Profit by Customer
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME,
	SUM((OI.UNIT_PRICE - P.COST_PRICE) * OI.QUANTITY) AS TOTAL_PROFIT
FROM
	CUSTOMERS C
	INNER JOIN ORDERS O ON O.CUSTOMER_ID = C.CUSTOMER_ID
	INNER JOIN ORDER_ITEMS OI ON OI.ORDER_ID = O.ORDER_ID
	INNER JOIN PRODUCTS P ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME
ORDER BY
	TOTAL_PROFIT DESC;

--6. Segment Revenue, Profit & Margin
SELECT
	C.CUSTOMER_SEGMENT,
	SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE,
	SUM((OI.UNIT_PRICE - P.COST_PRICE) * OI.QUANTITY) AS TOTAL_PROFIT,
	ROUND(
		SUM((OI.UNIT_PRICE - P.COST_PRICE) * OI.QUANTITY) / SUM(O.TOTAL_AMOUNT) * 100,
		2
	) AS PROFIT_MARGIN
FROM
	CUSTOMERS C
	INNER JOIN ORDERS O ON O.CUSTOMER_ID = C.CUSTOMER_ID
	INNER JOIN ORDER_ITEMS OI ON OI.ORDER_ID = O.ORDER_ID
	INNER JOIN PRODUCTS P ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY
	C.CUSTOMER_SEGMENT
ORDER BY
	TOTAL_REVENUE DESC;

--7. Repeat Customer % by Segment
SELECT
	CUSTOMER_SEGMENT,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM(IS_REPEAT::INT) AS REPEAT_CUSTOMERS,
	ROUND(SUM(IS_REPEAT::INT)::NUMERIC / COUNT(*) * 100, 2) AS REPEAT_CUSTOMER_PERCENTAGE
FROM
	(
		SELECT
			C.CUSTOMER_ID,
			C.CUSTOMER_SEGMENT,
			COUNT(O.ORDER_ID) AS ORDER_COUNT,
			COUNT(O.ORDER_ID) >= 2 AS IS_REPEAT
		FROM
			CUSTOMERS C
			INNER JOIN ORDERS O ON O.CUSTOMER_ID = C.CUSTOMER_ID
		GROUP BY
			C.CUSTOMER_ID,
			C.CUSTOMER_SEGMENT
	) T
GROUP BY
	CUSTOMER_SEGMENT
ORDER BY
	REPEAT_CUSTOMER_PERCENTAGE DESC;